DATASETS:
  NAME: "CIFAR10"
  # SEED: 42 (unused)
  CIFAR:
    SHUFFLE_INDICES: False
    TRAIN_INDICES: [0, 45000,]
    VALID_INDICES: [45000, 50000,]
    DATA_AUGMENTATION: "STANDARD_TRAIN_TRANSFORM"

DATALOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: False

MODEL:
  META_ARCHITECTURE:
    NAME: "ClassificationModelBase"
  PIXEL_MEAN: [0.4915, 0.4821, 0.4464,]
  PIXEL_STD: [0.2472, 0.2437, 0.2617,]
  BACKBONE:
    NAME: "build_resnet_backbone"
    RESNET:
      CHANNELS: 3
      IN_PLANES: 16
      FIRST_BLOCK:
        USE_NORM_LAYER: True
        USE_ACTIVATION: True
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1,]
        # POOL_KSP: [3, 2, 1,] (unused)
      BLOCK: "BasicBlock"
      SHORTCUT: "IdentityShortcut"
      NUM_BLOCKS: [5, 5, 5,]
      WIDEN_FACTOR: 1
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "BatchNorm2d"
      ACTIVATIONS: "ReLU"
  CLASSIFIER:
    NAME: "build_softmax_classifier"
    SOFTMAX_CLASSIFIER:
      FEATURE_DIM: 64
      NUM_CLASSES: 10
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"

SOLVER:
  NUM_EPOCHS: 200
  BATCH_SIZE: 512
  VALID_FREQUENCY: 20
  VALID_FINALE: 20
  OPTIMIZER:
    NAME: "SGD"
    SGD:
      BASE_LR: 0.4
      WEIGHT_DECAY: 0.0004
      MOMENTUM: 0.9
      NESTEROV: False
  SCHEDULER:
    NAME: "WarmupLinearDecayLR"
    WARMUP_LINEAR_DECAY_LR:
      MILESTONES: [5, 100, 180,]
      WARMUP_METHOD: "linear"
      WARMUP_FACTOR: 0.01
      GAMMA: 0.01

NUM_GPUS: 1
CUDNN_BENCHMARK: False
CUDNN_DETERMINISTIC: False
SEED: -1
OUTPUT_DIR: "./outputs/C10_R32_SGD/"
